name: Node.js CI  #nazwa pipeline

on: #definicja triggera (moe być na pusha, pull request, )
  push:
    branches:
      - master
  pull_request:
    branches:
      - master # jak wykonamy pull request do master

jobs: # kazdy job to OSOBNY docker
  install_and_run_tests: #to się pojawia w sekcji Actions jako nazwa
    runs-on: ubuntu-latest
    steps:
    - name: Git clone # akcja git clone
      uses: actions/checkout@v3
    - name: Setup Node.js 18 # kolejna akcja - instalacja node 18
      uses: actions/setup-node@v3 # w github actions nie trzeba brac obrazu node, on sam to ogarnia, w innych CI - trzeba pobrac obraz
      with:
        node-version: 18
    - name: Run unit tests
      run: |
        npm install
        chmod u+x ./node_modules/.bin/*
        npm test


